build env

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,19 +22,30 @@ jobs:
         node-version: [16.x]
         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
+  # Build node
+    - uses: actions/checkout@v2
+      with:
+          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@v3
+      env: 
+        ATLAS_URI: ${{ secrets.ATLAS_URI }}
+      with:
+        node-version: ${{ matrix.node-version }}
+        cache: 'npm'
+    - run: npm i
+    - run: npm run build --if-present --prod
+
   # Sonar Cloud
     steps:
     - uses: actions/checkout@v2
       with:
         fetch-depth: 0 
-    - name: Install dependencies
-      run: npm i
     - name: Test and coverage
-      env: 
-        ATLAS_URI: ${{ secrets.ATLAS_URI }} 
       run: npm run test
 
     - uses: actions/checkout@v2
+      if: success() || failure()        # run this step even if previous step failed
       with:
         fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
     - name: SonarCloud Scan
@@ -43,14 +54,4 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
-    # Build node
-    - uses: actions/checkout@v2
-      with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
-    - name: Use Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v3
-      with:
-        node-version: ${{ matrix.node-version }}
-        cache: 'npm'
-    - run: npm i
-    - run: npm run build --if-present --prod
+    
